### ISSUE TITLE
Cant get the game to properly run - constantly encountering error C2-12828-1

### ISSUE THREAD

**Issue by LeetyBOI** [v-atamanenko/masseffect-vita#3]
Really excited that you have managed to release these long awaited port, but unfortunately it seems I cannot get it running at all.

-followed the set-up instructions and installed the data files as described.
-successfully Verified that my build is exactly the correct one using sha1sum.
-I have libshacccg.suprx in the ur0:/data/ + kubridge.skprx (version 0,3) & Repatch_ex.skprx in my ur0:tai folder and in my  config.txt under *KERNEL.
-after encountering error C2-12828-1 when trying to boot the game, i have disabled Repatch_ex.skprx , placed FD_FIX in my  ur0:tai and in my config.txt under *KERNEL and restarted my VITA console. yet the game still wont boot.
-Tried to disable all my "optional plugins" in my config.txt file , than rebooted the console and tried to boot the game again - still unsuccessful.
-Uninstalled the game and reinstalled it - again without luck and again error  C2-12828-1 popped.

attaching crash dumps + my config.txt file :
[mass effect vita crash.zip](https://github.com/v-atamanenko/masseffect-vita/files/10298738/mass.effect.vita.crash.zip)

I will gladly appreciate your help in trying to determine what else can I do in order to try and get the game running.
Thanks a lot for your great work!

**Comment by th3on301** [comment]
Hello! I encounter the same issue. I have tried to re-install it but the app is not starting. I have checked the build version and is the same, I already have installed and updated the necessary plugins (other android ports works fine). I would appreciate if the issue can be checked. Thank you!

**Comment by th3on301** [comment]
Hello! I have deactivated the forcelang plugin from Autoplugin 2 and it fixed the issue for both ports, Mass Effect and Dead Space. This might be an incompatibility causing the error.

**Comment by LeetyBOI** [comment]
Thanks for you replay, but unfortunately this isn't the case for me.

i don't have the forcelang plugin , in addition I have also deleted Autoplugin 2 all together,
The C2-12828-1 error still pops every time i try to boot the game :(

**Comment by eugene-kirzhanov** [comment]
I'd had the same error until I've replaced "cache" by another one.
I've used "PowerVR _ Mali(ver4. ORIGINAL 2019) 100%📍.rar", you can find it the internet (not sure I can put the direct link here).
Or just ensure you use cache for PowerVR/Mail GPU, not for Adreno.

**Comment by v-atamanenko** [comment]
can't reproduce
